spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9093/C:/Users/haeun/IdeaProjects/jpa-book/data/jpashop
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true